services:

  api:

    build:
      context: .
      dockerfile: Dockerfile.api

    container_name: research-api

    ports:
      - "8000:8000"

    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434

    volumes:
      - ./chroma_db:/app/chroma_db
      - ./chat_memory.db:/app/chat_memory.db

  streamlit:

    build:
      context: .
      dockerfile: Dockerfile.streamlit

    container_name: research-ui

    ports:
      - "8501:8501"

    environment:
      - API_URL=http://api:8000

    depends_on:
      - api